export enum LoyaltyActionTypes {
    SET_INITIAL_POINTS_START = 'SET_INITIAL_POINTS_START',
    SET_INITIAL_POINTS_COMPLETED = 'SET_INITIAL_POINTS_COMPLETED',
    FETCH_LOYALTY_POINTS_START = 'FETCH_LOYALTY_POINTS_START',
    FETCH_LOYALTY_POINTS_COMPLETED = 'FETCH_LOYALTY_POINTS_COMPLETED'
}