export enum DiscountActionTypes {
    FETCH_ALL_DISCOUNTS_START = 'FETCH_ALL_DISCOUNTS_START',
    FETCH_DISCOUNT_BY_ID_START = 'FETCH_DISCOUNT_BY_ID_START',
    SAVE_REDEEMED_DISCOUNT_START = 'SAVE_REDEEMED_DISCOUNT_START',
    FETCH_ALL_DISCOUNTS_COMPLETED = 'FETCH_ALL_DISCOUNTS_COMPLETED',
    FETCH_DISCOUNT_BY_ID_COMPLETED = 'FETCH_DISCOUNT_BY_ID_COMPLETED',
    SAVE_REDEEMED_DISCOUNT_COMPLETED = 'SAVE_REDEEMED_DISCOUNT_COMPLETED',
    SET_DISCOUNT_ID = 'SET_DISCOUNT_ID'
}