export enum DiscountActionTypes {
    FETCH_ALL_DISCOUNTS_START = 'FETCH_ALL_DISCOUNTS_START',
    FETCH_DISCOUNT_BY_ID_START = 'FETCH_DISCOUNT_BY_ID_START',
    FETCH_ALL_DISCOUNTS_COMPLETED = 'FETCH_ALL_DISCOUNTS_COMPLETED',
    FETCH_DISCOUNT_BY_ID_COMPLETED = 'FETCH_DISCOUNT_BY_ID_COMPLETED'
}